
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[322] =
    {   0,
        0,    0,    0,    0,  101,   99,   97,   98,   96,   82,
       99,   99,   88,   81,   99,   76,   77,   86,   85,   73,
       84,   80,   87,   43,   43,   74,   70,   89,   75,   90,
       93,   39,   39,   78,   79,   91,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   71,   92,   72,   83,    6,    5,    6,    6,   69,
        0,   40,    0,    0,    0,   55,   72,   64,   56,    0,
        0,   53,   61,   51,   62,   52,   63,    0,   46,    2,
        1,   54,   47,   42,   43,   43,   43,    0,   43,   43,
       79,   71,   78,   60,   66,   68,   67,   59,    0,    0,

       39,   39,   39,   39,   57,   39,   39,   39,   39,   39,
       39,   14,   39,   39,   39,   39,   39,   39,   22,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       58,   65,    4,    3,    0,    0,   44,   48,    0,   46,
       46,    1,   46,    0,   47,   47,   42,   42,    0,   43,
       41,    0,   50,   49,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   20,   39,   23,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,    0,    0,    0,   46,    0,    0,
       46,   46,    0,   47,    0,    0,   45,   43,   43,   41,

       41,    0,   39,    7,   39,    9,   10,   39,   39,   39,
       39,   16,   17,   39,   39,   21,   24,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   36,   39,
       39,    0,    0,    0,    0,   46,    0,    0,    0,   45,
       45,    0,    0,    0,   39,    8,   11,   39,   39,   39,
       39,   19,   39,   39,   27,   39,   39,   39,   39,   39,
       39,   34,   39,   39,   38,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   39,   39,   39,   15,   18,
       39,   26,   28,   29,   30,   31,   32,   39,   39,   39,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   39,

       13,   39,   33,   39,   39,    0,   95,    0,    0,    0,
        0,    0,   12,   25,   35,   37,    0,   94,    0,   43,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   31,   30,   30,   32,   30,   30,
       33,   34,   35,   36,   30,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[329] =
    {   0,
        0,    0,   62,   63,  760,  789,  789,  789,  789,  735,
       61,   28,   45,   62,  723,  789,  789,  732,   58,  789,
       63,   72,   72,   80,   74,  729,  789,  102,  729,   53,
      789,  133,  175,  789,  789,  728,  696,  697,   87,   33,
       55,   51,  697,   87,  696,  704,   97,  685,  694,  692,
      697,  789,  104,  789,  789,  789,  789,  721,  724,  789,
       99,  789,  733,  693,  661,  789,  789,  789,  789,  106,
      145,  789,  789,  789,  789,  789,  789,  674,  179,  789,
        0,  789,  190,  192,  208,  130,  198,    0,  207,    0,
      789,  789,  789,  665,  789,  789,  789,  656,  124,  644,

      190,  191,  234,  236,  789,  245,  246,  251,  253,  254,
      260,  262,  265,  268,  274,  106,  263,  276,  287,  288,
      295,  303,  301,  304,  315,  316,  321,  323,  326,  329,
      789,  789,  789,  789,  628,  629,  789,  789,  329,  789,
      619,    0,  350,  339,  789,  616,  307,  334,   95,  364,
      335,  572,  789,  789,  331,  350,  388,  389,  395,  397,
      398,  403,  404,  406,  411,  409,  412,  414,  417,  422,
      423,  428,  430,  438,  433,  443,  449,  451,  450,  452,
      461,  460,  466,  463,  574,  565,  148,  465,  547,  461,
      789,  552,  214,  469,  531,  518,  489,    0,  482,  470,

      483,  512,  480,  486,  489,  509,  516,  522,  533,  534,
      535,  536,  541,  542,  543,  544,  549,  550,  552,  551,
      557,  558,  564,  563,  571,  573,  565,  574,  580,  581,
      582,  516,  465,  439,  367,  587,  409,  388,  383,  789,
      390,  372,  348,  355,  589,  590,  605,  612,  480,  614,
      615,  621,  622,  630,  627,  632,  633,  635,  638,  640,
      641,  643,  646,  648,  653,  347,  340,  336,  309,  309,
      299,  280,  270,  265,  264,  656,  659,  425,  661,  667,
      675,  677,  680,  688,  690,  691,  693,  696,  699,  701,
      305,  254,  236,  244,  227,  206,  189,  200,  194,  709,

      707,  712,  714,  715,  717,  208,  789,  202,  117,  116,
       95,   93,  720,  722,  723,  725,  131,  789,   51,  657,
      789,  764,  768,  772,  776,   80,  780,  784
    } ;

static yyconst flex_int16_t yy_def[329] =
    {   0,
      321,    1,  322,  322,  321,  321,  321,  321,  321,  321,
      323,  321,  321,  321,  324,  321,  321,  321,  321,  321,
      321,  321,  321,  321,   24,  321,  321,  321,  321,  321,
      321,  321,   32,  321,  321,  321,   32,   32,   32,   32,
       32,   32,   33,   33,   33,   33,   33,   33,   33,   33,
       33,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      323,  321,  323,  321,  321,  321,  321,  321,  321,  324,
      324,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      325,  321,  321,   24,   25,   85,  321,  326,  321,   25,
      321,  321,  321,  321,  321,  321,  321,  321,  323,  324,

       32,   33,   33,   33,  321,   33,   33,   32,   33,   33,
       32,   33,   33,   33,   33,  113,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  325,  321,  321,  321,  321,  321,  321,  321,   85,
      326,  321,  321,  321,   33,   33,   33,   33,   33,   33,
       32,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,   85,  321,  321,

      321,  321,   33,   33,   33,   33,   33,   33,   33,   32,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,   33,   33,   33,   33,  113,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,   33,   33,  113,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
      327,  321,  321,  321,  321,  321,  321,  321,  321,   33,

       33,   33,   33,   33,   33,  327,  321,  328,  321,  321,
      321,  321,   33,   33,   33,   33,  328,  321,  321,  321,
        0,  321,  321,  321,  321,  321,  321,  321
    } ;

static yyconst flex_uint16_t yy_nxt[854] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   32,   32,   33,
       33,   33,   34,    6,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   33,   44,   33,   45,   33,   33,   33,
       33,   46,   47,   48,   49,   50,   51,   33,   33,   33,
       52,   53,   54,   55,   57,   57,   62,   64,   66,   67,
       68,   73,   65,  111,   58,   58,   97,   98,   75,   59,
       59,   74,  112,  151,   80,   69,   76,   77,   78,   81,
       79,   79,   90,   90,   63,   82,   83,  116,   84,   84,

      117,  113,  240,  114,   62,  321,   85,   86,   85,   92,
       87,   88,  115,  197,  197,  137,   85,   85,   85,   85,
       86,   85,   93,  108,   94,   95,   89,  131,  119,   62,
      109,  321,   63,  318,   87,  120,  110,   88,   99,   71,
      123,  124,  100,  149,  200,  149,  320,  321,  150,  150,
      125,  101,  101,  126,   70,  166,  319,   63,  102,  101,
      101,  101,  102,  103,  102,  132,  188,  188,  191,  101,
      101,  101,  101,  101,  101,  102,  102,  102,  102,  104,
      102,  102,  102,  102,  102,  102,  102,  103,  102,  102,
      102,  102,  102,  102,  102,  321,  321,   79,   79,  321,

      321,  102,  102,  102,  318,  102,  139,  140,  143,  143,
      307,  102,  102,  102,  102,  102,  102,  144,  145,  139,
      140,  102,  147,  321,  321,  141,   85,   85,   87,  102,
      144,  145,  194,  194,  312,   85,  146,   87,  148,  321,
      311,  321,  310,  321,   89,  321,  147,  152,   85,  321,
      321,  321,   87,   89,  321,  321,  321,  147,  321,  321,
      321,   87,  321,  321,  103,  321,  103,  321,  321,  321,
      321,  321,  321,  321,  321,  103,  155,  321,  145,  321,
      104,  321,  104,  321,  309,  321,  157,  140,  103,  159,
      103,  104,  321,  321,  308,  103,  321,  321,  156,  103,

      321,  161,  160,  158,  321,  155,  321,  307,  321,  321,
      321,  104,  321,  321,  167,   87,  162,  163,  299,  103,
      321,  321,  164,  298,  321,  321,  321,  165,  321,  168,
      321,  321,  321,  297,  321,  321,  321,  147,  321,  296,
      321,  169,  187,  170,  187,  171,  174,  188,  188,  295,
      173,  176,  193,  148,  193,  321,  172,  194,  194,  321,
      178,  147,  294,  175,  147,  200,  177,  180,  143,  143,
      182,  179,  183,  184,  196,  181,  293,  190,  191,  292,
      148,  201,  150,  150,  203,  236,  236,  291,  147,  200,
      190,  191,  198,  321,  321,  275,  192,  321,  321,  204,

      321,  274,  321,  321,  321,  198,  321,  321,  321,  321,
      199,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  205,  273,  321,  321,  321,  206,
      272,  321,  321,  321,  210,  321,  271,  321,  321,  321,
      211,  270,  321,  321,  212,  215,  207,  321,  321,  208,
      209,  214,  321,  213,  321,  321,  321,  321,  321,  321,
      321,  321,  269,  216,  217,  321,  321,  218,  321,  321,
      321,  321,  321,  222,  235,  321,  235,  102,  301,  236,
      236,  220,  219,  188,  188,  321,  221,  194,  194,  321,
      226,  321,  268,  140,  321,  321,  223,  145,  321,  229,

      200,  227,  230,  224,  225,  228,  140,  197,  197,  231,
      145,  141,   87,  200,  321,  146,  201,  240,  321,  267,
      102,  321,  242,  243,  200,  321,  278,  321,   89,  201,
      240,  321,  102,  245,  246,  241,   87,  200,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  266,  244,  321,  321,  321,  321,
      321,  239,  321,  321,  321,  247,  321,  248,  321,  321,
      321,  250,  321,  321,  238,  321,  321,  321,  249,  321,
      321,  321,  237,  251,  321,  321,  252,  256,  321,  321,

      234,  259,  253,  254,  255,  236,  236,  257,  258,  260,
      321,  233,  261,  262,  321,  191,  263,  321,  232,  321,
      321,  321,  265,  321,  321,  202,  321,  321,  191,  276,
      321,  321,  321,  192,  264,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  279,  321,  195,  321,  321,  189,
      277,  321,  321,  280,  321,  321,  321,  186,  321,  185,
      321,  283,  321,  285,  284,  281,  321,   71,  282,  154,
      321,  288,  321,  287,  321,  321,  321,   87,  153,  321,
      138,  286,  290,  321,  289,  321,  321,  321,  321,  321,

      321,  321,  321,   89,  321,  321,  321,  103,  321,  136,
      321,   87,  321,  300,  321,  302,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  135,  321,  321,  134,  303,  133,  304,
      130,  129,  128,  127,  122,  121,  118,  305,  107,  313,
      106,  105,   96,   91,  315,   72,   71,  316,   60,  321,
      321,  321,  321,  314,   56,   56,   56,   56,   61,   61,
       61,   61,   70,   70,  321,   70,  142,  321,  142,  142,
      306,  306,  306,  306,  317,  317,  317,  317,    5,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321
    } ;

static yyconst flex_int16_t yy_chk[854] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   11,   12,   13,   13,
       14,   19,   12,   40,    3,    4,   30,   30,   21,    3,
        4,   19,   40,  326,   23,   14,   21,   21,   22,   23,
       22,   22,   25,   25,   11,   23,   24,   42,   24,   24,

       42,   41,  319,   41,   61,   25,   24,   24,   24,   28,
       24,   24,   41,  149,  149,   70,   24,   24,   24,   24,
       24,   24,   28,   39,   28,   28,   24,   53,   44,   99,
       39,   25,   61,  317,   24,   44,   39,   24,   32,   70,
       47,   47,   32,   86,  312,   86,  311,   71,   86,   86,
       47,   32,   32,   47,   71,  116,  310,   99,  116,   32,
       32,   32,   32,   32,   32,   53,  187,  187,  309,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   33,   33,  101,  102,   79,   79,  101,

      102,   33,   33,   33,  308,   33,   79,   79,   83,   83,
      306,   33,   33,   33,   33,   33,   33,   83,   83,   79,
       79,   33,   84,   84,   85,   79,   85,   85,   87,   33,
       83,   83,  193,  193,  299,   85,   83,   89,   84,  103,
      298,  104,  297,  103,   87,  104,   84,   89,   85,   84,
      106,  107,   87,   89,  106,  107,  108,  296,  109,  110,
      108,   89,  109,  110,  103,  111,  104,  112,  117,  111,
      113,  112,  117,  114,  113,  106,  104,  114,  295,  115,
      103,  118,  104,  115,  294,  118,  107,  293,  103,  109,
      104,  106,  119,  120,  292,  113,  119,  120,  106,  106,

      121,  111,  110,  108,  121,  113,  123,  291,  122,  124,
      123,  113,  122,  124,  117,  275,  112,  113,  274,  113,
      125,  126,  114,  273,  125,  126,  127,  115,  128,  118,
      127,  129,  128,  272,  130,  129,  155,  147,  130,  271,
      155,  120,  139,  121,  139,  122,  124,  139,  139,  270,
      123,  125,  144,  147,  144,  156,  122,  144,  144,  156,
      126,  147,  269,  124,  148,  151,  125,  128,  143,  143,
      129,  127,  129,  130,  148,  128,  268,  143,  143,  267,
      148,  151,  150,  150,  155,  235,  235,  266,  148,  151,
      143,  143,  150,  157,  158,  244,  143,  157,  158,  156,

      159,  243,  160,  161,  159,  150,  160,  161,  162,  163,
      150,  164,  162,  163,  166,  164,  165,  167,  166,  168,
      165,  167,  169,  168,  157,  242,  169,  170,  171,  158,
      241,  170,  171,  172,  161,  173,  239,  172,  175,  173,
      162,  238,  175,  174,  163,  166,  159,  174,  176,  160,
      160,  165,  176,  164,  177,  179,  178,  180,  177,  179,
      178,  180,  237,  168,  170,  182,  181,  171,  184,  182,
      181,  183,  184,  175,  190,  183,  190,  278,  278,  190,
      190,  173,  172,  188,  188,  203,  174,  194,  194,  203,
      179,  204,  234,  188,  205,  204,  176,  194,  205,  182,

      200,  180,  183,  177,  178,  181,  188,  197,  197,  184,
      194,  188,  199,  201,  206,  194,  200,  197,  206,  233,
      249,  207,  199,  201,  200,  207,  249,  208,  199,  201,
      197,  208,  249,  203,  205,  197,  199,  201,  209,  210,
      211,  212,  209,  210,  211,  212,  213,  214,  215,  216,
      213,  214,  215,  216,  217,  218,  220,  219,  217,  218,
      220,  219,  221,  222,  232,  202,  221,  222,  224,  223,
      227,  196,  224,  223,  227,  208,  225,  209,  226,  228,
      225,  211,  226,  228,  195,  229,  230,  231,  210,  229,
      230,  231,  192,  214,  245,  246,  215,  221,  245,  246,

      189,  224,  218,  219,  220,  236,  236,  222,  223,  225,
      247,  186,  226,  227,  247,  236,  228,  248,  185,  250,
      251,  248,  231,  250,  251,  152,  252,  253,  236,  245,
      252,  253,  255,  236,  230,  254,  255,  256,  257,  254,
      258,  256,  257,  259,  258,  260,  261,  259,  262,  260,
      261,  263,  262,  264,  250,  263,  146,  264,  265,  141,
      248,  276,  265,  251,  277,  276,  279,  136,  277,  135,
      279,  256,  280,  258,  257,  253,  280,  100,  254,   98,
      281,  261,  282,  260,  281,  283,  282,  320,   94,  283,
       78,  259,  264,  284,  263,  285,  286,  284,  287,  285,

      286,  288,  287,  320,  289,  288,  290,  276,  289,   65,
      290,  320,  301,  277,  300,  281,  301,  302,  300,  303,
      304,  302,  305,  303,  304,  313,  305,  314,  315,  313,
      316,  314,  315,   64,  316,   63,   59,  288,   58,  289,
       51,   50,   49,   48,   46,   45,   43,  290,   38,  300,
       37,   36,   29,   26,  304,   18,   15,  305,   10,    5,
        0,    0,    0,  302,  322,  322,  322,  322,  323,  323,
      323,  323,  324,  324,    0,  324,  325,    0,  325,  325,
      327,  327,  327,  327,  328,  328,  328,  328,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexicalAnalyzer.l"
#line 2 "lexicalAnalyzer.l"
#include <stdio.h>
#include "y.tab.h"
int lineCount=1;
int nestedCommentCount=0;
int commentFlag=0;
char *tablePtr;
void addToken(char*);

#line 771 "lex.yy.c"

#define INITIAL 0
#define DETECT_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 23 "lexicalAnalyzer.l"



#line 994 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 322 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 789 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "lexicalAnalyzer.l"
{ lineCount++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "lexicalAnalyzer.l"
{ BEGIN(DETECT_COMMENT);
					  nestedCommentCount++; 
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "lexicalAnalyzer.l"
{ nestedCommentCount++;
					  if(nestedCommentCount>1)
					  	commentFlag = 1;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "lexicalAnalyzer.l"
{ BEGIN(INITIAL); lineCount++;
						 if(nestedCommentCount>0)
                                			nestedCommentCount--;
                            			if(nestedCommentCount==0)
                            				BEGIN(INITIAL);
                    			}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 44 "lexicalAnalyzer.l"
{lineCount++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "lexicalAnalyzer.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "lexicalAnalyzer.l"
{  return(AUTO); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "lexicalAnalyzer.l"
{  return(BREAK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "lexicalAnalyzer.l"
{  return(CASE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "lexicalAnalyzer.l"
{  return(CHAR); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "lexicalAnalyzer.l"
{  return(CONST); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "lexicalAnalyzer.l"
{  return(CONTINUE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "lexicalAnalyzer.l"
{  return(DEFAULT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "lexicalAnalyzer.l"
{  return(DO); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "lexicalAnalyzer.l"
{  return(DOUBLE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "lexicalAnalyzer.l"
{  return(ELSE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "lexicalAnalyzer.l"
{  return(ENUM); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "lexicalAnalyzer.l"
{  return(EXTERN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "lexicalAnalyzer.l"
{  return(FLOAT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "lexicalAnalyzer.l"
{  return(FOR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "lexicalAnalyzer.l"
{  return(GOTO); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "lexicalAnalyzer.l"
{  return(IF); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "lexicalAnalyzer.l"
{  return(INT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "lexicalAnalyzer.l"
{  return(LONG); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "lexicalAnalyzer.l"
{  return(REGISTER); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "lexicalAnalyzer.l"
{  return(RETURN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "lexicalAnalyzer.l"
{  return(SHORT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "lexicalAnalyzer.l"
{  return(SIGNED); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "lexicalAnalyzer.l"
{  return(SIZEOF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "lexicalAnalyzer.l"
{  return(STATIC); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "lexicalAnalyzer.l"
{  return(STRUCT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "lexicalAnalyzer.l"
{  return(SWITCH); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "lexicalAnalyzer.l"
{  return(TYPEDEF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "lexicalAnalyzer.l"
{  return(UNION); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "lexicalAnalyzer.l"
{  return(UNSIGNED); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "lexicalAnalyzer.l"
{  return(VOID); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "lexicalAnalyzer.l"
{  return(VOLATILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "lexicalAnalyzer.l"
{  return(WHILE); }
	YY_BREAK
/*"printf"		{ return(PRINTF);}
"scanf"			{ return(SCANF);}
*/
case 39:
YY_RULE_SETUP
#line 85 "lexicalAnalyzer.l"
{  addToken(yytext); return(IDENTIFIER); }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 86 "lexicalAnalyzer.l"
{  addToken(yytext); return(STRING_LITERAL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 91 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 92 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 96 "lexicalAnalyzer.l"
{  return(ELLIPSIS); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 97 "lexicalAnalyzer.l"
{  return(RIGHT_ASSIGN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "lexicalAnalyzer.l"
{  return(LEFT_ASSIGN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "lexicalAnalyzer.l"
{  return(ADD_ASSIGN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "lexicalAnalyzer.l"
{  return(SUB_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "lexicalAnalyzer.l"
{  return(MUL_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 102 "lexicalAnalyzer.l"
{  return(DIV_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 103 "lexicalAnalyzer.l"
{  return(MOD_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 104 "lexicalAnalyzer.l"
{  return(AND_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 105 "lexicalAnalyzer.l"
{  return(XOR_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 106 "lexicalAnalyzer.l"
{  return(OR_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "lexicalAnalyzer.l"
{  return(RIGHT_OP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 108 "lexicalAnalyzer.l"
{  return(LEFT_OP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 109 "lexicalAnalyzer.l"
{  return(INC_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 110 "lexicalAnalyzer.l"
{  return(DEC_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 111 "lexicalAnalyzer.l"
{  return(PTR_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 112 "lexicalAnalyzer.l"
{  return(AND_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 113 "lexicalAnalyzer.l"
{  return(OR_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 114 "lexicalAnalyzer.l"
{  return(LE_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 115 "lexicalAnalyzer.l"
{  return(GE_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 116 "lexicalAnalyzer.l"
{  return(EQ_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 117 "lexicalAnalyzer.l"
{  return(NE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 118 "lexicalAnalyzer.l"
{  return(';'); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 119 "lexicalAnalyzer.l"
{  makeList("{",'p',lineCount); return('{'); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 120 "lexicalAnalyzer.l"
{  makeList("}",'p',lineCount); return('}'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 121 "lexicalAnalyzer.l"
{  return(','); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 122 "lexicalAnalyzer.l"
{  return(':'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 123 "lexicalAnalyzer.l"
{  return('='); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 124 "lexicalAnalyzer.l"
{  return('('); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 125 "lexicalAnalyzer.l"
{  return(')'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 126 "lexicalAnalyzer.l"
{  return('['); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 127 "lexicalAnalyzer.l"
{  return(']'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 128 "lexicalAnalyzer.l"
{  return('.'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 129 "lexicalAnalyzer.l"
{  return('&'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 130 "lexicalAnalyzer.l"
{  return('!'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 131 "lexicalAnalyzer.l"
{  return('~'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 132 "lexicalAnalyzer.l"
{  return('-'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 133 "lexicalAnalyzer.l"
{  return('+'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 134 "lexicalAnalyzer.l"
{  return('*'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 135 "lexicalAnalyzer.l"
{  return('/'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 136 "lexicalAnalyzer.l"
{  return('%'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 137 "lexicalAnalyzer.l"
{  return('<'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 138 "lexicalAnalyzer.l"
{  return('>'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 139 "lexicalAnalyzer.l"
{  return('^'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 140 "lexicalAnalyzer.l"
{  return('|'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 141 "lexicalAnalyzer.l"
{  return('?'); }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 144 "lexicalAnalyzer.l"
{ lineCount++; }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 145 "lexicalAnalyzer.l"
{ lineCount++; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 147 "lexicalAnalyzer.l"
{}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 148 "lexicalAnalyzer.l"
{}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 149 "lexicalAnalyzer.l"
{lineCount++;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 150 "lexicalAnalyzer.l"
{ }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 152 "lexicalAnalyzer.l"
ECHO;
	YY_BREAK
#line 1570 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DETECT_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 322 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 322 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 321);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 152 "lexicalAnalyzer.l"


yywrap()
{
	return(1);
}

void addToken(char *yytext)
{
  int len = strlen(yytext);
  tablePtr = (char*)malloc((len+1)*sizeof(char));
  strcpy(tablePtr, yytext);
}


